services:
  mongodb:
    image: mongo:8.0.11
    container_name: fuelstats-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - fuelstats-mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  fuelstats-server:
    build:
      context: .
      dockerfile: Dockerfile   # or Dockerfile.bun
    container_name: fuelstats-server
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "6060:6060"
    environment:
      NODE_ENV: production
    env_file:
      - .env.fuelstats
    volumes:
      - .env.production:/app/dist/.env.production:ro
      - ./fuelstats-logs:/app/dist/logs

volumes:
  fuelstats-mongo-data:

